# verbosity level for all logged messages (debug, info, warning, error)
loglevel: info

# set debug to true to enable django debbuging mode, docs:
# https://docs.djangoproject.com/en/dev/ref/settings/#debug
debug: false

# secret key, must be set to some random value
# each node in single cluster must have the same value for it!
secretkey: changeme

# list of domains this site can serve, any domain will be allowed if not
# specified, details can be found in django docs:
# https://docs.djangoproject.com/en/1.5/ref/settings/#allowed-hosts
#domains:
#  - "www.u-paas.org"
#  - "u-paas.org"
